In [3]:
import numpy as np
arr_1d = np.array([1,2,3,4,5,6,7,8,9])
print("1D array:",arr_1d)

1D array: [1 2 3 4 5 6 7 8 9]


In [5]:
array_2d_random = np.random.randint(1, 21, (3, 3))
print("2D array with random integers:", array_2d_random)


2D array with random integers: [[17  3 16]
 [ 8  7 17]
 [14 12 13]]


In [6]:
arr_3d = np.ones((2,3,4))
print("3D array of ones:", arr_3d)

3D array of ones: [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [7]:
arr1 =np.array([1,2,3,4,5])
arr2 = np.array([10,9,8,7,6])
arr_sum = arr1 + arr2
print("Element-wise addition of 1D arrays:",arr_sum)

Element-wise addition of 1D arrays: [11 11 11 11 11]


In [8]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
arr_mult = arr_1 * arr_2
print("Element-wise multiplication of 2D arrays:", arr_mult)


Element-wise multiplication of 2D arrays: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [9]:
array_stat = np.array([1,3,5,7,9,11])
mean_val = np.mean(array_stat)
median_val = np.median(array_stat)
std_dev = np.std(array_stat)
print("Mean:", mean_val, "Median:", median_val,"Standard Deviation:", std_dev)


Mean: 6.0 Median: 6.0 Standard Deviation: 3.415650255319866


In [11]:
normal_dist = np.random.normal(0,1,1000)
print("Array of random numbers from normal distribution:", normal_dist)

Array of random numbers from normal distribution: [ 1.81257902  2.13622157 -0.71347964  0.61061574 -1.37436678 -2.29335152
 -0.44023068 -0.98063135 -0.24124022  0.50283496  0.50025452 -0.9223627
  0.2174007   0.64366446 -0.32167088  0.93008995  0.12975301 -0.82291971
  0.31543897 -1.67480437  2.2190295   0.69736077 -0.26874421  0.81570573
  0.76396354 -0.35852171 -0.0633207  -1.4917501   0.66140613 -0.18716371
  0.30034193  0.13948733 -0.07007324  0.32689517 -0.44735671 -1.18627194
  0.19426458  0.69708218  0.51364017 -0.55444215  1.88487907  0.42428635
 -0.53713115 -0.04179664  0.02137768  0.42302196  0.17556365 -1.46106638
  0.598      -1.40187698  0.39789994  0.78759453 -2.3188928   0.39562537
  1.28211361 -1.02267647  1.22062681 -0.96205023  1.10343663 -1.17662695
 -0.51005536 -0.23427147 -1.86631457  1.2674324   0.15455281  2.66114437
 -0.84514251 -0.52116359 -0.90463557 -1.83980121  2.81209953  2.02994511
 -0.95325324 -0.12991378 -0.58120641 -0.2698735   0.10104686  1.52043314
 -

In [13]:
uniform_dist = np.random.randint(10, 51, (5,5))
print("2D array with random integers from uniform distribution:",uniform_dist)

2D array with random integers from uniform distribution: [[49 11 24 26 39]
 [18 40 30 42 12]
 [11 18 42 42 31]
 [44 44 34 42 48]
 [36 19 27 15 33]]


In [15]:
cumulative_sum = np.cumsum(arr1)
print("Cumulative sum of 1D array:", cumulative_sum)


Cumulative sum of 1D array: [ 1  3  6 10 15]


In [16]:
correlation_matrix = np.corrcoef(arr_1)
print("Correlation coefficient matrix of 2D array:", correlation_matrix)


Correlation coefficient matrix of 2D array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
die_rolls = np.random.randint(1, 7, 1000)
roll_frequencies = np.bincount(die_rolls)[1:]
print("Frequency of each outcome from rolling a die 1000 times:", roll_frequencies)


Frequency of each outcome from rolling a die 1000 times: [169 189 165 145 161 171]
