In [44]:
import pandas as pd
import numpy as np
list_data = [1, 2, 3, 4, 5]
series_from_list = pd.Series(list_data)
array_data = np.array([10, 20, 30, 40, 50])
series_from_array = pd.Series(array_data)
dict_data = {'a': 100, 'b': 200, 'c': 300}
series_from_dict = pd.Series(dict_data)
print("Series from list:\n", series_from_list)
print("Series from array:\n", series_from_array)
print("Series from dict:\n", series_from_dict)

Series from list:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
Series from array:
 0    10
1    20
2    30
3    40
4    50
dtype: int32
Series from dict:
 a    100
b    200
c    300
dtype: int64


In [47]:
srs = pd.Series (list_data, index=['A','B','C','D','E'])
print("Series with custom index:\n", srs)

Series with custom index:
 A    1
B    2
C    3
D    4
E    5
dtype: int64


In [8]:
srs1 = pd.Series([1,2,3,4,5])
srs2 = pd.Series([10,20,30,40,50])

srs_sum = srs1 + srs2
srs_diff = srs1 - srs2
srs_prd = srs1 * srs2
srs_quot = srs1 / srs2
print("Sum of series:\n", series_sum)

In [48]:
ele = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print("Element by label:\n", ele)

Element by label:
 a    10
b    20
c    30
d    40
e    50
dtype: int64


In [49]:
filter_srs = srs[srs > 20]
print("Filtered series:\n", filter_srs)

Filtered series:
 Series([], dtype: int64)


In [50]:
data_dict = {
    'Name' : ['Alice', 'Bob', 'Charlie'],
    'Age' : [25,30,35],
    'City' : ['New York' , 'Los Angeles', 'Chicago']
}
df_from_dict = pd.DataFrame(data_dict)
print("DataFrame from dict:\n", df_from_dict)

DataFrame from dict:
       Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [51]:
array_data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df_from_array = pd.DataFrame(array_data, columns=['A', 'B', 'C'], index=['Row1', 'Row2', 'Row3'])
print("DataFrame from array:\n", array_data)

DataFrame from array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
import pandas as pd

# Sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 22],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [70000, 80000, 90000, 100000, 75000]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('data.csv', index=False)


In [35]:

df_from_csv = pd.read_csv('data.csv')


In [52]:
first_five_rows = df_from_csv.head()
last_five_rows = df_from_csv.tail()
print("DataFrame from CSV first five rows:\n", first_five_rows)
print("DataFrame from CSV last five rows:\n", last_five_rows)

DataFrame from CSV first five rows:
       Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000
4      Eva   22      Phoenix   75000
DataFrame from CSV last five rows:
       Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000
4      Eva   22      Phoenix   75000


In [43]:
mean_values = df_from_csv.select_dtypes(include='number').mean()
median_values = df_from_csv.select_dtypes(include='number').median()
std_values = df_from_csv.select_dtypes(include='number').std()

print("Summary Statistics:\n", summary_statistics)
print("Mean Values:\n", mean_values)
print("Median Values:\n", median_values)
print("Standard Deviation Values:\n", std_values)

Summary Statistics:
              Age         Salary
count   5.000000       5.000000
mean   30.400000   83000.000000
std     7.300685   12041.594579
min    22.000000   70000.000000
25%    25.000000   75000.000000
50%    30.000000   80000.000000
75%    35.000000   90000.000000
max    40.000000  100000.000000
Mean Values:
 Age          30.4
Salary    83000.0
dtype: float64
Median Values:
 Age          30.0
Salary    80000.0
dtype: float64
Standard Deviation Values:
 Age           7.300685
Salary    12041.594579
dtype: float64


In [53]:
age_series = df_from_dict['Age']
print("Extracted column as Series:\n", age_series)

Extracted column as Series:
 0    25
1    30
2    35
Name: Age, dtype: int64


In [54]:
filtered_df = df_from_dict[df_from_dict['Age'] > 30]
print("Filtered DataFrame:\n", filtered_df)

Filtered DataFrame:
       Name  Age     City
2  Charlie   35  Chicago


In [55]:
multiple_conditions_df = df_from_dict[(df_from_dict['Age'] > 25) & (df_from_dict['City'] == 'Chicago')]
print("DataFrame with multiple conditions:\n", multiple_conditions_df)

DataFrame with multiple conditions:
       Name  Age     City
2  Charlie   35  Chicago


In [41]:
df_from_dict['Salary'] = [50000, 60000, 70000]


In [42]:
df_from_dict.drop(columns=['Salary'], inplace=True)
