Linear Algebra Tasks


    Matrix Creation and Manipulation



In [2]:
import numpy as np
zero_matrix = np.zeros((3,3))

identity_matrix = np.eye(3)

random_matrix = np.random.rand(3, 3)

print("Zero Matrix:\n", zero_matrix)
print("Identity Matrix:\n", identity_matrix)
print("Random Matrix:\n", random_matrix)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Matrix:
 [[0.3841849  0.41350595 0.66474277]
 [0.1938337  0.70226158 0.87078713]
 [0.90489513 0.32754462 0.81469846]]


In [4]:
A = np.array([[12,4,6],[5,9,10],[5,0,4]])
B = np.array([[5,5,6],[9,8,2],[3,0,11]])

add_result = A + B

sub_result = A - B

mult_result = np.dot(A,B)

print("Addition:\n",add_result)
print("Subtraction:\n",sub_result)
print("Multiplication:\n",mult_result)

Addition:
 [[17  9 12]
 [14 17 12]
 [ 8  0 15]]
Subtraction:
 [[ 7 -1  0]
 [-4  1  8]
 [ 2  0 -7]]
Multiplication:
 [[114  92 146]
 [136  97 158]
 [ 37  25  74]]


In [5]:
transpose_A = A.T

det_A = np.linalg.det(A)

try:
    inv_A = np.linalg.inv(A)
except np.linalg.LinAlgError:
    inv_A = "Matrix is singular and cannot be inverted"


print("Transpose:\n", transpose_A)
print("Determinant:\n", det_A)
print("Inverse:\n", inv_A)

Transpose:
 [[12  5  5]
 [ 4  9  0]
 [ 6 10  4]]
Determinant:
 282.00000000000006
Inverse:
 [[ 0.12765957 -0.05673759 -0.04964539]
 [ 0.10638298  0.06382979 -0.31914894]
 [-0.15957447  0.07092199  0.31205674]]


Solving Linear Equations

In [6]:
coefficients = np.array([[3, 1], [1, 2]])

constants = np.array([9, 8])

solution = np.linalg.solve(coefficients, constants)
print("Solution:", solution)

Solution: [2. 3.]


In [7]:
from scipy.linalg import lu

P, L, U = lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

Q, R = np.linalg.qr(A)
print("Q:\n", Q)
print("R:\n", R)

P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L:
 [[ 1.          0.          0.        ]
 [ 0.41666667  1.          0.        ]
 [ 0.41666667 -0.22727273  1.        ]]
U:
 [[12.          4.          6.        ]
 [ 0.          7.33333333  7.5       ]
 [ 0.          0.          3.20454545]]
Q:
 [[-0.86154979  0.24206886 -0.44624503]
 [-0.35897908 -0.91203004  0.19833112]
 [-0.35897908  0.33106477  0.87265694]]
R:
 [[-13.92838828  -6.67701088 -10.19500585]
 [  0.          -7.23999487  -6.34362812]
 [  0.           0.           2.79646884]]


Eigenvalues and Eigenvectors

In [8]:
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:",eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues: [17.97185538+0.j          3.51407231+1.82824973j  3.51407231-1.82824973j]
Eigenvectors:
 [[ 0.69974101+0.j          0.04741958+0.18436188j  0.04741958-0.18436188j]
 [ 0.66907166+0.j         -0.84297484+0.j         -0.84297484-0.j        ]
 [ 0.25041091+0.j          0.43874011-0.24629779j  0.43874011+0.24629779j]]


In [9]:
reconstructed_A = eigvecs @ np.diag(eigvals) @ np.linalg.inv(eigvecs)
print("Reconstructed A:\n", reconstructed_A)

Reconstructed A:
 [[ 1.20000000e+01-6.83804741e-16j  4.00000000e+00+5.86681698e-16j
   6.00000000e+00+6.18780379e-16j]
 [ 5.00000000e+00-9.22237360e-16j  9.00000000e+00+1.17222792e-15j
   1.00000000e+01+1.71640089e-15j]
 [ 5.00000000e+00-7.32704082e-16j -1.52655666e-16+2.29736917e-16j
   4.00000000e+00-6.33726168e-17j]]


Vector Operations

In [10]:
u = np.array([2, 9, 10])
v = np.array([12, 23, 9])

vec_add = u + v
print("Vector Addition:", vec_add)

dot_product = np.dot(u, v)
print("Dot Product:", dot_product)

cross_product = np.cross(u, v)
print("Cross Product:", cross_product)

Vector Addition: [14 32 19]
Dot Product: 321
Cross Product: [-149  102  -62]


In [12]:
norm_u = u / np.linalg.norm(u)
print("Normalized Vector:", norm_u)

l1_norm = np.linalg.norm(u, 1)
l2_norm = np.linalg.norm(u, 2)
print("L1 Norm:", l1_norm)
print("L2 Norm:", l2_norm)

Normalized Vector: [0.14704292 0.66169316 0.73521462]
L1 Norm: 21.0
L2 Norm: 13.601470508735444


Matrix Decomposition

In [14]:
data = np.array([[2.5, 2.4],[0.5, 0.7], [2.2, 2.9], [1.9, 2.2], [3.1, 3.0]])

data_mean = np.mean(data, axis=0)
centered_data = data - data_mean
U, S, Vt = np.linalg.svd(centered_data)

projected_data = centered_data @ Vt.T
print("Projected Data:\n", projected_data)

Projected Data:
 [[-0.44362444 -0.20099093]
 [ 2.17719404 -0.05500992]
 [-0.57071239  0.36808609]
 [ 0.12902465  0.06747325]
 [-1.29188186 -0.17955849]]


Calculus

Numerical Differentiation

In [15]:
def f(x):
    return x**2 + 3*x + 2

x = np.linspace(-10, 10, 100)
h = 1e-5

forward_diff = (f(x+h) - f(x)) / h
print("Forward Difference:", forward_diff)

backward_diff = (f(x) - f(x - h)) / h
print("Backward Difference:", backward_diff)

central_diff = (f(x+h) - f(x-h)) / (2*h)
print("Central Difference:", central_diff)

Forward Difference: [-16.99999    -16.5959496  -16.19190919 -15.78786879 -15.38382838
 -14.97978798 -14.57574757 -14.17170717 -13.76766677 -13.36362636
 -12.95958596 -12.55554556 -12.15150515 -11.74746475 -11.34342434
 -10.93938394 -10.53534353 -10.13130313  -9.72726273  -9.32322232
  -8.91918192  -8.51514152  -8.11110111  -7.70706071  -7.3030203
  -6.8989799   -6.49493949  -6.09089909  -5.68685869  -5.28281828
  -4.87877788  -4.47473747  -4.07069707  -3.66665667  -3.26261626
  -2.85857586  -2.45453545  -2.05049505  -1.64645465  -1.24241424
  -0.83837384  -0.43433343  -0.03029303   0.37374737   0.77778778
   1.18182818   1.58586859   1.98990899   2.39394939   2.7979898
   3.2020302    3.60607061   4.01011101   4.41415141   4.81819182
   5.22223222   5.62627263   6.03031303   6.43435343   6.83839384
   7.24243424   7.64647465   8.05051505   8.45455545   8.85859586
   9.26263626   9.66667667  10.07071707  10.47475747  10.87879788
  11.28283828  11.68687869  12.09091909  12.49495949  12.8

Numerical Integration

In [16]:
def f(x):
    return np.sin(x)

x = np.linspace(0, np.pi, 100)
y = f(x)

trapz_integral = np.trapz(y, x)
print("Trapezoidal Integral:", trapz_integral)

from scipy.integrate import simps

simps_integral = simps(y, x)
print("Simpson's Integral:",simps_integral)

Trapezoidal Integral: 1.9998321638939927
Simpson's Integral: 2.0000000534993037


C:\Users\abuba\AppData\Local\Temp\ipykernel_11108\3765455774.py:12: DeprecationWarning: 'scipy.integrate.simps' is deprecated in favour of 'scipy.integrate.simpson' and will be removed in SciPy 1.14.0
  simps_integral = simps(y, x)


Partial Derivatives

In [18]:
def f(x, y):
    return x**2 + y**2

x, y = np.meshgrid(np.linspace(-5, 5, 100), np.linspace(-5, 5, 100))
h = 1e-5

partial_x = (f(x + h,y) - f(x, y)) / h
print("Partial Derivative w.r.t x:\n", partial_x)

partial_y = (f(x, y+h) - f(x,y)) / h
print("Partial Derivative w.r.t y:\n", partial_y)

Partial Derivative w.r.t x:
 [[-9.99999   -9.7979698 -9.5959496 ...  9.5959696  9.7979898 10.00001  ]
 [-9.99999   -9.7979698 -9.5959496 ...  9.5959696  9.7979898 10.00001  ]
 [-9.99999   -9.7979698 -9.5959496 ...  9.5959696  9.7979898 10.00001  ]
 ...
 [-9.99999   -9.7979698 -9.5959496 ...  9.5959696  9.7979898 10.00001  ]
 [-9.99999   -9.7979698 -9.5959496 ...  9.5959696  9.7979898 10.00001  ]
 [-9.99999   -9.7979698 -9.5959496 ...  9.5959696  9.7979898 10.00001  ]]
Partial Derivative w.r.t y:
 [[-9.99999   -9.99999   -9.99999   ... -9.99999   -9.99999   -9.99999  ]
 [-9.7979698 -9.7979698 -9.7979698 ... -9.7979698 -9.7979698 -9.7979698]
 [-9.5959496 -9.5959496 -9.5959496 ... -9.5959496 -9.5959496 -9.5959496]
 ...
 [ 9.5959696  9.5959696  9.5959696 ...  9.5959696  9.5959696  9.5959696]
 [ 9.7979898  9.7979898  9.7979898 ...  9.7979898  9.7979898  9.7979898]
 [10.00001   10.00001   10.00001   ... 10.00001   10.00001   10.00001  ]]


Optimization

In [23]:
from scipy.optimize import minimize

def objective(x):
    return x[0]**2 + x[1]**2

cons = ({'type':'eq','fun': lambda x: x[0]+x[1] -1})
x0 = [0.5, 0.5]

result = minimize(objective, x0, constraints=cons)
print("Optimal Solution:", result)


Optimal Solution:  message: Optimization terminated successfully
 success: True
  status: 0
     fun: 0.5
       x: [ 5.000e-01  5.000e-01]
     nit: 1
     jac: [ 1.000e+00  1.000e+00]
    nfev: 3
    njev: 1
