In [3]:
import numpy as np
arr = np.arange(25).reshape(5, 5)
sub_array = arr[1:4, 1:4]

In [4]:
arr_3d = np.arange(24).reshape(4, 3, 2)
sub_array_3d = arr_3d[:2, :, 1]


In [5]:
arr = np.arange(10)
fancy_indexed = arr[[1, 3, 4, 7]]


In [6]:
arr_2d = np.arange(25).reshape(5, 5)
fancy_indexed_2d = arr_2d[[0, 2, 3], :][:, [1, 3]]


In [7]:
arr_random = np.random.randint(0, 20, size=10)
greater_than_10 = arr_random[arr_random > 10]


In [8]:
arr_2d = np.random.randint(0, 20, size=(5, 5))
arr_2d[arr_2d > 15] = 0


In [9]:
arr_2d = np.random.randint(0, 10, size=(4, 3))
arr_1d = np.array([1, 2, 3])
broadcasted_sum = arr_2d + arr_1d


In [10]:
arr_2d = np.random.randint(0, 10, size=(3, 3))
arr_1d = np.array([1, 2, 3])
broadcasted_product = arr_2d * arr_1d


In [11]:
arr1 = np.random.randint(0, 10, size=(3, 1))
arr2 = np.random.randint(0, 10, size=(1, 4))
elementwise_sum = arr1 + arr2


In [12]:
arr_3d = np.random.randint(0, 10, size=(2, 3, 4))
arr_2d = np.random.randint(0, 10, size=(3, 4))
broadcasted_3d_sum = arr_3d + arr_2d


In [13]:
arr_2d = np.random.randint(0, 10, size=(5, 5))
sliced_arr = arr_2d[::2, ::2]
arr_1d = np.array([1, 2, 3])
sliced_sum = sliced_arr + arr_1d[:sliced_arr.shape[1]]


In [37]:
import numpy as np
arr_3d = np.random.randint(0, 10, size=(4, 3, 2))
sub_arr_3d = arr_3d[:2, :, :]
arr_2d = np.random.randint(0, 10, size=(2, 2))
reshaped_arr_2d = arr_2d[:, np.newaxis, :]
broadcasted_subtraction = sub_arr_3d - reshaped_arr_2d
print("arr_3d:\n", arr_3d)
print("sub_arr_3d:\n", sub_arr_3d)
print("arr_2d:\n", arr_2d)
print("reshaped_arr_2d:\n", reshaped_arr_2d)
print("broadcasted_subtraction:\n", broadcasted_subtraction)


arr_3d:
 [[[2 4]
  [5 5]
  [0 8]]

 [[1 4]
  [4 9]
  [4 9]]

 [[6 4]
  [4 8]
  [7 3]]

 [[2 2]
  [1 9]
  [5 1]]]
sub_arr_3d:
 [[[2 4]
  [5 5]
  [0 8]]

 [[1 4]
  [4 9]
  [4 9]]]
arr_2d:
 [[6 9]
 [5 1]]
reshaped_arr_2d:
 [[[6 9]]

 [[5 1]]]
broadcasted_subtraction:
 [[[-4 -5]
  [-1 -4]
  [-6 -1]]

 [[-4  3]
  [-1  8]
  [-1  8]]]


In [39]:
arr_3d = np.random.randint(0, 10, size=(4, 3, 2))
sub_arr_3d = arr_3d[:2, :, :]
arr_2d = np.random.randint(0, 10, size=(2, 2))
reshaped_arr_2d = arr_2d[:, np.newaxis, :]
broadcasted_subtraction = sub_arr_3d - reshaped_arr_2d
print("arr_3d:\n", arr_3d)
print("sub_arr_3d:\n", sub_arr_3d)
print("arr_2d:\n", arr_2d)
print("reshaped_arr_2d:\n", reshaped_arr_2d)
print("broadcasted_subtraction:\n", broadcasted_subtraction)


arr_3d:
 [[[4 1]
  [9 6]
  [8 8]]

 [[3 5]
  [6 3]
  [5 2]]

 [[5 3]
  [8 0]
  [4 6]]

 [[9 6]
  [8 0]
  [5 3]]]
sub_arr_3d:
 [[[4 1]
  [9 6]
  [8 8]]

 [[3 5]
  [6 3]
  [5 2]]]
arr_2d:
 [[2 7]
 [1 5]]
reshaped_arr_2d:
 [[[2 7]]

 [[1 5]]]
broadcasted_subtraction:
 [[[ 2 -6]
  [ 7 -1]
  [ 6  1]]

 [[ 2  0]
  [ 5 -2]
  [ 4 -3]]]


In [16]:
arr_2d = np.random.randint(0, 10, size=(5, 5))
diagonal_elements = np.diag(arr_2d)


In [17]:
arr_2d = np.random.randint(0, 10, size=(5, 5))
reversed_rows = arr_2d[:, ::-1]


In [18]:
arr_3d = np.random.randint(0, 10, size=(4, 5, 6))
sub_arr_3d = arr_3d[:2, :3, :4]
arr_1d = np.array([1, 2, 3, 4])
broadcasted_addition = sub_arr_3d + arr_1d


In [19]:
arr_2d = np.random.randint(0, 10, size=(5, 5))
arr_2d[:, -1] = arr_2d[:, 0] + arr_2d[:, 1]


In [20]:
arr_2d = np.arange(36).reshape(6, 6)
sub_array_2x2 = arr_2d[1:3, 1:3]


In [21]:
arr_3d = np.arange(6).reshape(3, 2, 1)
sub_array_3d_2 = arr_3d[:2, :, 0]


In [22]:
arr = np.arange(10)
fancy_indexed_arr = arr[[1, 3, 4, 6]]


In [23]:
arr_2d = np.arange(36).reshape(6, 6)
fancy_indexed_2d = arr_2d[[0, 2, 2], :][:, [1, 3]]



In [24]:
arr_random = np.random.randint(0, 20, size=10)
greater_than_8 = arr_random[arr_random > 8]


In [25]:
arr_random = np.random.randint(0, 20, size=10)
greater_than_8 = arr_random[arr_random > 8]


In [26]:
arr_2d = np.random.randint(0, 20, size=(6, 6))
arr_2d[arr_2d > 13] = 0


In [27]:
arr_2d = np.random.randint(0, 10, size=(4, 3))
arr_1d = np.array([1, 2, 3])
broadcasted_sum_extended = arr_2d + arr_1d


In [28]:
arr_2d = np.random.randint(0, 10, size=(3, 3))
arr_1d = np.array([1, 2, 3])
broadcasted_product_extended = arr_2d * arr_1d


In [29]:
arr1 = np.random.randint(0, 10, size=(3, 1))
arr2 = np.random.randint(0, 10, size=(1, 4))
elementwise_sum_extended = arr1 + arr2


In [30]:
arr_3d = np.random.randint(0, 10, size=(2, 3, 4))
arr_2d = np.random.randint(0, 10, size=(3, 4))
broadcasted_3d_sum_extended = arr_3d + arr_2d


In [31]:
arr_2d = np.random.randint(0, 10, size=(6, 6))
sliced_arr_extended = arr_2d[::2, ::2]
arr_1d = np.array([1, 2, 3])
sliced_sum_extended = sliced_arr_extended + arr_1d[:sliced_arr_extended.shape[1]]


In [32]:
arr_3d = np.random.randint(0, 10, size=(3, 2, 1))
sub_arr_3d_extended = arr_3d[:, :, :]
arr_2d = np.random.randint(0, 10, size=(2, 1))
broadcasted_subtraction_extended = sub_arr_3d_extended - arr_2d


In [33]:
arr_2d = np.random.randint(0, 10, size=(6, 6))
diagonal_elements_extended = np.diag(arr_2d)


In [34]:
arr_2d = np.random.randint(0, 10, size=(6, 6))
reversed_rows_extended = arr_2d[:, ::-1]


In [35]:
arr_3d = np.random.randint(0, 10, size=(7, 6, 5))
sub_arr_3d_extended = arr_3d[:2, :3, :4]
arr_1d = np.array([1, 2, 3, 4])
broadcasted_addition_extended = sub_arr_3d_extended + arr_1d


In [36]:
arr_2d = np.random.randint(0, 10, size=(6, 6))
arr_2d[:, -1] = arr_2d[:, 0] + arr_2d[:, 1]
